# This is the YAML config file to make this a little more abstractish

# Stuff about you.
user_config:
  # Your Name. This will be used for the page title
  name: 'Daniel Bear'

  # The file you want to parse to be your resume
  # Must be a format supported by github-markup
  file: 'resume.md'

  # The pdf output file you want to use/update
  pdf_file: 'resume.pdf'

  # The google analytics key you wish to use.
  # TODO
  gkey: 'UA-37554479-1'

# For github pages to work, this needs to be the GitHub repository this file is
# stored in.
github:
  # git url
  remote: 'git@github.com:danhbear/Resume.git'

  # git url
  git_url: 'https://github.com/danhbear/Resume'

  # html url
  html_url: 'http://danhbear.github.com/Resume/'
